name: Caching Primes

on:
   workflow_dispatch:
    inputs:
      environment:
        description: 'enter one of the environments '
        required: true
        default: 'linux'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Prime Numbers
      run: echo this is test
