name: Caching with npm
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/hello-world-javascript-action@main
      with:
        who-to-greet: 'Mona the Octocat'
  test:
    runs-on: ubuntu-latest
    steps:
steps:
  - uses: actions/checkout@v3
  - uses: actions/setup-node@v3
    with:
      node-version: 14
      cache: 'npm'
  - run: npm ci
  - run: npm test
