on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Please enter Name?'
        required: false
        default: 'World'
      who-to-greet:
        description: 'Who to greet'
        required: false
        default: 'World'


jobs:
  manual:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          # make file runnable, might not be necessary
          chmod +x "${GITHUB_WORKSPACE}/sample.sh"

          # run script
          "${GITHUB_WORKSPACE}/sample.sh ${{ inputs.who-to-greet }}"
