on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Please enter Name?'
        required: false
        default: 'World'
      who-to-greet:
        description: 'Who to greet'
        required: false
        default: 'World'


jobs:
  manual:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        run: PATH/sample.sh
        shell: bash
        with:
          who-to-greet: ${{ github.event.inputs.name }}
